# Site settings
title: Erdin Mujezinović
email: erdin.mujezinovic@hhu.de
description: Academic webpage of Erdin Mujezinović
baseurl: ""
url: "https://erd-ling.github.io"

# Google analytics ID: Uncomment and your own, if you like
# google_analytics: XX
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
  Erdin Mujezinović<br/>
  PhD student in General Linguistics<br/>
  Heinrich-Heine University Düsseldorf
  Institute for Linguistics<br/>

location: >
  Linguistics I: Phonetics and Phonology<br/>
  Office: 23.21.04.053<br/>
  Universitätsstraße 1<br/>
  40225 Düsseldorf

contact: >
  <a href="mailto:erdin.mujezinovic@hhu.de" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Erdin via email</a> <br/>
  <a href="https://github.com/sbryngelson/academic-website-template"><i class="fa fa-github fa-1x"></i> Use this site as a template!</a>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: publications
  - name: talks
  - name: research
  - name: software
#  - name: team
  - name: teaching
  - name: experiments

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

plugins: ["jekyll/scholar"]

scholar:
  last_name: Mujezinović
  first_name: [Erdin]

  style: citesty
  locale: en

  source: /assets/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
